language: php

php:
  - 7.1
  - 7.2
  - nightly

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.1

before_install:
  - travis_retry composer self-update

install:
  - composer require --no-update
  - composer --prefer-dist install